#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket"
        /usr/bin/aesdsocket -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        killall aesdsocket
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
